name = "CbiomesProcessing"
uuid = "c98f7216-5713-11e9-18a6-f5cd6f6a6fff"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.0"

[deps]
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
